kind: Service
apiVersion: v1
metadata:
  name: db
  labels:
    name: db-service
    app: demo-voting-app 
spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: demo-voting-app 
  ports:
  - targetPort: 5432
    port: 5432
    
