apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    name: myapp-rs
    app: myapp
    type: front-end
spec:
  template:
    metadata:
     name: myapp-pod
     labels:
       name: myapp-pod
       app: myapp
       type: front-end
    spec:
     containers:
     - name: nginx-container
       image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
      # app: myapp

