kind: Service
apiVersion: v1
metadata:
  name: be-service

spec:
  type: ClusterIP
  selector:
    app: myapp
    type: back-end
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30001
